### PR TITLE
Concatenate uns

### PR DESCRIPTION
**Pull request by giovp**
See https://github.com/theislab/anndata/issues/295#issuecomment-600014248 for context.

I've added the `concatenate_uns` function in `utils`, not sure if it is correct.

This follows #338 to support multiple visium anndata.

### CODE REVIEW

**Comment by ivirshup** [comment]
Sorry for taking so long on the review!

Could this function be defined so that it checks keys at every level, not just the first two?

**Comment by giovp** [comment]
No problem at all, thank you for all the help w/ all these PRs ! Really appreciate !

Docs are still missing, will work on them as soon as you think such approach makes sense.

**Comment by giovp** [comment]
Hi @ivirshup this would also be ready for review. Thank you!!!

**Comment by ivirshup** [comment]
Superseded by #350

**Pull request closed without merging**
