### PR TITLE
Export Raw

### PR DESCRIPTION
**Pull request by ivirshup**
#174

### CODE REVIEW

**Comment by falexwolf** [comment]
Fine!

**Comment by flying-sheep** [comment]
It should be linked here, right? https://anndata.readthedocs.io/en/latest/api.html

**Comment by ivirshup** [comment]
I guess... I'm not a fan of `Raw` since it requires implementing a bunch of things twice, and can mostly be replaced by `layers`. I personally don't want to advertise it too much just in case we're able to deprecate it. I do, however, think we should export from a consistent location, mostly so it can be used for type annotations and dispatch.

If other people like it, I'd be happy to hear that point of view. It's just something which I don't use, but have to code around.

**Comment by falexwolf** [comment]
I agree with you, Isaac. :) I'm essentially entirely stopped using it myself in the past year. I would also not advertise too much but rather work towards more consistent solutions.

`.layers` completely works as a replacement if one never actually filters on variables, but replaces every filtering stepped by a purely annotation based solution. It wouldn't be hard at all to make this the default in Scanpy, generally; it's just that I still lack bandwidth...

**Comment by LuckyMD** [comment]
I currently use it to store uncorrected data in the single cell tutorial. Could change that to layers in the next update though. Is there a layers equivalent to `use_raw` for plotting functions?

**Comment by ivirshup** [comment]
@LuckyMD Mostly the `layer` key word argument.

@falexwolf no worries. I think `Raw` would take a while to fully excise since there's so much logic dealing with it. The main argument I can see for `Raw` is that a boolean filter (like we have with highly variable genes) has to be re-applied each time it's used, so there's a performance cost. There are ways around this, but it'd take some consideration to choose one.

Right now, some plotting functions have `use_raw` as `None`, which turns to `True` if raw is defined. This would be a big change in behavior if raw is deprecated, since there's no convention for what "raw" is in layers. I also think the current behavior could be more consistently documented.

**Comment by falexwolf** [comment]
@LuckyMD It's perfectly fine that your tutorial uses it; the Seurat-based tutorial also uses it and people can continue. I just agreed with Isaac that we shouldn't advertise beyond because I also don't like it. Thinking a bit more, though, adding`Raw` to the docs is more a clarification than an advertisement as long as the tutorials legitly keep using it.

@ivirshup All that logic should be maintained and would be replaced with a special slot in `.layers` called 'raw'. Then it really boils down to merely a more elegant implementation. For instance, it would be nice to be able to generate an AnnData from any `layer` (something that people have asked for `Raw`)... But, it's not a priority...

**Pull request merged**
