### PR TITLE
Switch to flit

### PR DESCRIPTION
**Pull request by flying-sheep**
See theislab/scanpy#1527

### CODE REVIEW

**Comment by ivirshup** [comment]
To check sure this won't cause CI problems after merging, can you start a pr on scanpy that makes the `anndata-dev` build point to this PR? We'll just delete that pr once this is ready.

**Comment by flying-sheep** [comment]
Done, too bad such a nice issue number is wasted on it lol theislab/scanpy#1700

**Comment by flying-sheep** [comment]
d339903 can probably be removed, see theislab/scanpy#1702

**Review by ivirshup — APPROVED** [review]
Just to be sure, did you not have to update the `azure` setup?

**Comment by flying-sheep** [comment]
No need it’s just standard pip usage and simply works. If we want, we can add a build check later like scanpy has

**Pull request merged**
