### PR TITLE
read/write nested anndata objects

### PR DESCRIPTION
**Pull request by joshua-gould**

### CODE REVIEW

**Comment by Koncopd** [comment]
Hi, @joshua-gould . Can you give a small example of usage?

**Comment by joshua-gould** [comment]
Do you mean an example use case, or how to write a nested anndata object?
If the latter, an example is in the tests-
https://github.com/theislab/anndata/pull/620/files#diff-8d332e04f0346b46fa930793fe4afb902279e898581ac81f911ff737d286f188
.

**Comment by ivirshup** [comment]
Hey @joshua-gould. I do think it's reasonable to support this, but .... I'm partway through a large refactor of this code which it would be difficult to merge this with.

I've implemented this feature as a commit to the refactor PR here: https://github.com/theislab/anndata/pull/554/commits/a4259f7edc15507be620171c1efc82da6bbb3bd0

I'm going to close this PR in favour of that one, please take a look and see if I've covered the use cases.

**Comment by joshua-gould** [comment]
Looks good, thanks

**Pull request closed without merging**
