### PR TITLE
Unifiy zarr and h5ad backends

### PR DESCRIPTION
**Pull request by joshua-gould**
This commit unifies the zarr and h5ad backends for reading. It supports reading zarr files in backed mode by doing a few instanceof checks that need to be fixed.

Remaining to dos:
Unify backends for writing
Update AnnDataFileManager to work with zarr files and other future formats that support the mapping interface.

### CODE REVIEW

**Comment by flying-sheep** [comment]
Nice approach!

Stylistically, please use black to format the code, use relative imports instead of `import anndata.thing` and delete code instead of commenting it out.

Why did you choose name `mapping` for the HDF5 module?

**Comment by joshua-gould** [comment]
Thanks. I will reformat and make the changes you requested.
The base classes are in the mapping package because h5py and zarr
groups both implement most of the Python dictionary convention.

**Comment by flying-sheep** [comment]
Hmm, I think it should be named in a way that reflects that this is about disk-backed persistence using hdf5.

**Comment by joshua-gould** [comment]
Is there a use case for changing to/from backed mode after instantiating an AnnData object? It might make the code simpler to remove this ability.

**Comment by flying-sheep** [comment]
How do we shift back and forth?

**Comment by joshua-gould** [comment]
By setting AnnData.filename to a string (on) or None (off)

**Comment by flying-sheep** [comment]
Ah! Well, I’ll let @ivirshup take over, he’s been working on this

**Comment by ivirshup** [comment]
Thanks for making this PR! It's nice to see people contributing the features they want to see. However, my inclination would be to not accept it, since it replicates existing work.

As previous mentioned to you in #219, improving backed mode is something I'm already working on. As you've noted, the zarr and h5ad backends are almost identical. The main reason I've been doing that, along with other efforts to make storage consistent (like the contents of `alignedmappings.py`), was to make a more useful/ flexible backing ability.

Like you've noticed with `adata.filename = path/to/file.h5ad`, there's some limiting behaviour for backed mode at the moment. Another issue to me is that we support sparse and dense matrices all over the place, but in backed mode only `.X` is kept on disk. I think these behaviors should change, but I think the changes should be bundled with a larger overhaul, with many tests, and plenty of warning.

My current plans involve setting an abstraction layer between the `AnnData` object and the actual data, so that it's easier to improve and experiment with data management. I think this may be similar to what you were thinking with the updates to the `AnnDataFileManager`. The work is still in draft stages, but accomplishes much of what is covered here.

If you're wondering why you haven't seen this yet, it's because I would like to get 0.7 out and release before adding more new features. There's already a fair amount of the current backed mode that doesn't work as expected (modification largely, access time frequently), and I think it's going to require some more time to work out the kinks. However, there are already large performance and consistency improvements on master which are worth getting out to users.

Again, thanks for putting in the work on this PR. Sorry if this is disappointing. If you'd like I could let you know when I think we could use more contributions in this area. Seeing as it looks like your TODOs and implemented code are quite similar to what I've been doing, it could also useful to get your input as these features are added – if you'd be interested in that.

**Comment by joshua-gould** [comment]
Makes sense. I’d be happy to contribute to your refactoring efforts. Thanks.

**Pull request closed without merging**
