### PR TITLE
update write_loom to write layers

### PR DESCRIPTION
**Pull request by VolkerBergen**

### CODE REVIEW

**Comment by flying-sheep** [comment]
Could you please add a test validating that an AnnData object with layers can be correctly written and read again?

**Comment by VolkerBergen** [comment]
Sure, done.

**Comment by flying-sheep** [comment]
where? i mean in this PR’s branch. and please make it a separate test, not new asserts in an old one :smiley:

**Comment by flying-sheep** [comment]
he added it in another PR, but should add it in this one.

@VolkerBergen if you don’t want to do the whole checkout dance you can also go to [the file on branch patch-3](https://github.com/VolkerBergen/anndata/blob/patch-3/anndata/readwrite/write.py) online and edit it there

**Comment by flying-sheep** [comment]
looks great, thank you!

**Pull request merged**
