### PR TITLE
[WIP] Make obsm/varm creation lazy

### LINKED ISSUE #360: Anndata not properly garbage collected
**Description**
When an anndata object is deleted in the current scope the underlying memory is not (reliably) freed  as it is for numpy and others. The memory is kept allocated until the process exits. This lead to huge memory consumption if several anndata files are read sequentially in the same process. 

**Version:**
Python 3.7.6 and Python 3.8.2
anndata==0.7.1
scanpy==1.4.6

**Code to Reproduce:**
```python
import scanpy as sc
import numpy as np
import os
import tracemalloc

def display_top(snapshot, key_type='lineno'):
    snapshot = snapshot.filter_traces((
        tracemalloc.Filter(False, "<frozen importlib._bootstrap>"),
        tracemalloc.Filter(False, "<unknown>"),
    ))
    top_stats = snapshot.statistics(key_type)
    total = sum(stat.size for stat in top_stats)
    return total

def trace_function(func, arg, n):
    total = np.zeros(n)
    data = func(arg).copy()
    tracemalloc.start()
    for i in range(n):
        data = func(arg).copy()
        snapshot = tracemalloc.take_snapshot()
        total[i] = display_top(snapshot)
    tracemalloc.stop()
    return total
```

```python
_NP_FILENAME = 'numpydata.npy'
_ANNDATA_FILENAME = 'testfile.h5ad'
_RUNS = 5
```

```python
data = sc.read(_ANNDATA_FILENAME)
np.save(_NP_FILENAME, np.random.rand(*data.shape))
```

```python
total_np = trace_function(np.load, _NP_FILENAME, _RUNS)
total = trace_function(sc.read, _ANNDATA_FILENAME, _RUNS)
```

```python
display(total_np)
```

    array([1.74600576e+09, 1.74602235e+09, 1.74602685e+09, 1.74602814e+09,
           1.74602672e+09])

```python


display(total)
```

    array([1.74998379e+09, 2.62655985e+09, 3.50312986e+09, 2.62657418e+09,
           3.50315218e+09])

```python
import matplotlib.pyplot as plt

plt.plot(np.arange(_RUNS), total_np, label='numpy')
plt.plot(np.arange(_RUNS), total, label='anndata')
plt.legend()
plt.show()
```

output_10_0

### PR DESCRIPTION
**Pull request by fhausmann**
Makes `AxisArrays` creation for `obsm` and `varm` lazy, meaning only create these objects if needed and no reference inside the `AnnData` object is needed.

This should fixes the increased memory consumption when creating multiple `AnnData` objects.

Should fix #360 and was proposed here https://github.com/theislab/anndata/pull/363#issuecomment-624367298

### CODE REVIEW

**Comment by fhausmann** [comment]
Status Update:

- [x] obsm lazy
- [ ] varm lazy
- [ ] Add test for memory usage
- [ ] Fix circular reference in AnnDataFileManager

**Comment by kaizhang** [comment]
When will this be merged? I would like to use `obsm` to store a large matrix and do not want it to be loaded to memory.

**Comment by ivirshup** [comment]
@kaizhang I think it's fair to say this PR has stalled and a new one will need to be created, will close for now but will start tracking issue. Shouldn't be awful just needs to get done.

While this does cause temporary increases in memory usage (until a gc cycle collects these) it should not cause an on-disk array to be loaded into memory.

**Comment by kaizhang** [comment]
@ivirshup Are you suggesting that matrices stored in `obsm` or `varm` will not be loaded into memory when opening an anndata file? I know `X` will not be loaded into memory by default. But it seems to me that all other annotations will be kept in memory. Is this documented somewhere?

**Comment by ivirshup** [comment]
> Are you suggesting that matrices stored in obsm or varm will not be loaded into memory when opening an anndata file?

No, I'm saying that the issue this PR is addressing is orthogonal to loading things into memory. This is more of a memory-leak/ poor garbage collection issue.

>  I know X will not be loaded into memory by default.

It only won't be loaded if you pass `ad.read_h5ad(..., backed=True)`

**Comment by kaizhang** [comment]
Thanks for the clarification. How do I tell `anndata` not to load my matrix then? It seems to me that the only way is to use the upcoming `filespec` feature to define custom file format. Will `filespec` also support subsetting, e.g., get access to current view, in future?

**Pull request closed without merging**
