### PR TITLE
enable concat layers

### PR DESCRIPTION
**Pull request by VolkerBergen**
Addressing issue #63 . So far, only join=='inner' is considered. A test has not been written yet.

### CODE REVIEW

**Comment by falexwolf** [comment]
Thank you! :smile:

Looks good, except that one should output a warning if one tries to do an "outer" join and layers is non-empty in one of the passed AnnDatas. One should also output a warning if the layers are not consistently set in all the passed AnnDatas.

Finally, a mini-test would be nice. Just take a chunk of this test https://github.com/theislab/anndata/blob/9dce27428d5403713e41ce89a0a10da97ee18616/anndata/tests/test_base.py#L266 and adapt it with a layers attribute `test_concatenate_layers`.

**Comment by VolkerBergen** [comment]
Thanks for your comments. I added a few lines in test_concatenate (imho better than having a separate test_concatenate_layers). Further, two warnings (logger.info) are included for 1) 'outer' join and non-empty layers, and 2) inconsistent layers among AnnDatas.

**Comment by falexwolf** [comment]
This is a lot better! I don't really see how come that the coverage still went down by 1%... The only non-covered lines are the logging lines... Hm.

I'm fixing the conflict and merging this into master.

Thank you! 🙂

**Comment by flying-sheep** [comment]
Maybe our codecov setup is wrong, and the bot didn’t update the overview.

When you look at the site, everything is green: https://codecov.io/gh/theislab/anndata/pull/94?src=pr&el=continue

**Pull request merged**
