### PR TITLE
Faster backed access (rebased)

### PR DESCRIPTION
**Pull request by flying-sheep**
See #227. @ivirshup please check

- [x] is the diff correct? I checked this using

    ```bash
    interdiff \
        <(curl https://patch-diff.githubusercontent.com/raw/theislab/anndata/pull/241.diff) \
        <(curl https://patch-diff.githubusercontent.com/raw/theislab/anndata/pull/227.diff)
    ```

- [ ] which commits should be squashed?

Sorry that some commits got reassigned to me, I can fix that if you want.

### CODE REVIEW

**Comment by ivirshup** [comment]
Wow, thanks for wading into that!

Any chance you know about the working state of any of the commits? I.e. any idea if tests pass at any of the intermediate commits?

For changes to the commit history:

* 66d52bb could be squashed into 69363ad, I
* bf06cfa should probably have it's own commit, since a lot changed

> Sorry that some commits got reassigned to me, I can fix that if you want.

I do like seeing more green on my commit history...

**Comment by flying-sheep** [comment]
Done.

> Any chance you know about the working state of any of the commits? I.e. any idea if tests pass at any of the intermediate commits?

Sure, but I didn’t bother. If you do, feel free:

```bash
git checkout faster-backend-access
git rebase --interactive --exec "PYTHONPATH=. pytest" master
```

**Comment by ivirshup** [comment]
I'll check that out when I have a change. Can this be merged otherwise?

**Comment by flying-sheep** [comment]
Done!

**Pull request merged**
