### PR TITLE
AlignedMapping (obsm, varm, layers refactor)

### PR DESCRIPTION
**Pull request by ivirshup**
Supersedes #140.

This work is now ready for a final review and merging. The history is a bit unwieldy, but I'm happy to cut it down if requested.

This PR refactors `obsm`, `varm`, and `layers` to have a shared root class and backend. Now they are all `Mappings` whose contents have restrictions on their `shape`. This means they're much more flexible, and can contain array-like objects of multiple types. Also this centralizes the code for taking views of these objects and makes their behavior consistent. Currently, this works best with `scipy.sparse.spmatrix` and `np.ndarray` type objects. `pd.DataFrames` work alright, but need to have reading and writing implemented. That will follow in another pull request, since I think this has diverged far enough from master and is otherwise self contained.

This PR can close the following issues:

* #142 This no longer occurs.
* #148 A user can now modify `.obs` of a view, a copy of the view is made first.
* #136 obsm and varm now support sparse matrices.
* #45 Since obsm and varm values are only expected to align on their first axis, more shapes are allowed.

Work to follow from this PR includes:

* Modifying the scanpy docs to make clear the copy on modify nature of views of anndata objects
* Allowing dataframes in to be stored in an AnnData's mappings (mostly as issue of IO)
* Add `obsp`, `varp` attributes for storing pairwise measurements (i.e. cell-cell knn graphs, or gene correlation matrices). This is currently commented out pending test and IO implementation.
* (further in the future) Allow lazy and backed loading for arrays in aligned mapping.

### CODE REVIEW

**Comment by LuckyMD** [comment]
Is this also something that is/will go towards being able to write pandas dataframes from `.uns` to .h5ad?

**Comment by ivirshup** [comment]
Yes, though a little tangentially. I want to be able to store dataframes anywhere in an AnnData, so `.uns` is included in that. This requires defining an on disk representation for these dataframes. Since it'll be written to disk, it's probably worth making sure we're happy with how it's done, or at least having some versioning info.

My draft of how to do this keeps the current "basically a recarray" format, but adds a tag so we know to decode it as a data frame. It also stores the categorical variables with the hdf dataset, so we don't need to put them in `.uns`. This is probably a non-optimal solution, but would be very easy to implement.

<details>
<summary> Draft implementation </summary>

```python
import numpy as np
import pandas as pd
from pandas.api.types import (
    is_string_dtype,
    is_categorical
)
from anndata import h5py
import h5py as _h5py

# This is basically a modified `df_to_records_fixed_width`
def _df_to_hdf5_recarray(df, var_len_str=True):
    """Convert a pandas dataframe into a recarray h5py can write."""
    if is_string_dtype(df.index):
        if var_len_str:
            index = df.index.values.astype(h5py.special_dtype(vlen=str))
        else:
            max_len_index = 0 if 0 in df.shape else df.index.map(len).max()
            index = df.index.values.astype('S{}'.format(max_len_index))
    else:
        index = df.index.values
    names = ['index']
    arrays = [index]
    formats = [index.dtype]
    for k in df.columns:
        names.append(k)
        if is_string_dtype(df[k]) and not is_categorical(df[k]):
            if var_len_str:
                arrays.append(df[k].values)
                formats.append(h5py.special_dtype(vlen=str))
            else:
                lengths = df[k].map(len)
                if is_categorical(lengths):
                    lengths = lengths.cat.as_ordered()
                arrays.append(df[k].values.astype('S{}'.format(lengths.max())))
                formats.append(arrays[-1].dtype)
        elif is_categorical(df[k]):
            arrays.append(df[k].cat.codes)
            formats.append(_make_h5_cat_dtype(df[k].values))
        else:
            arrays.append(df[k].values)
            formats.append(arrays[-1].dtype)
    assert len(formats) == len(arrays)
    return np.rec.fromarrays(
        arrays,
        dtype={'names': names, 'formats': formats})

def _make_h5_cat_dtype(s):
    """This creates a hdf5 enum dtype based on a pandas categorical array."""
    dt = h5py.special_dtype(enum=(
        s.codes.dtype,
        dict(zip(s.categories, np.unique(s.codes)))
    ))
    return dt

def write_dataframe(f, key, value, dataset_kwargs={}):
    recs = _df_to_hdf5_recarray(value)
    f.create_dataset(key, data=recs, **dataset_kwargs)
    f[key].attrs["source_type"] = "dataframe"  # Add a tag so we know how to decode it

def read_dataframe(dataset):
    df = pd.DataFrame(dataset[:])
    df.set_index(df.columns[0], inplace=True)
    dt = dataset.dtype
    for col in dt.names[1:]:
        check = _h5py.check_dtype(enum=dt[col])
        if not isinstance(check, dict):
            continue
        mapper = {v: k for k, v in check.items()}
        df[col] = pd.Categorical(df[col].map(mapper), ordered=False)
    return df
```

</details>

**Comment by LuckyMD** [comment]
Okay, so once this is merged, I will change the `sc.tl.marker_gene_overlap()` function to allow storing the DataFrames inplace in `adata.uns`.

**Comment by ivirshup** [comment]
Adding IO for dataframes will be in a separate pull request. I'm aiming for these to be in the same release, but I'd hold off for just a bit more.

**Comment by ivirshup** [comment]
@falexwolf, did the questions you mentioned with `read_loom` (https://github.com/theislab/anndata/pull/140#issuecomment-499036092) get resolved?

**Comment by falexwolf** [comment]
Yes, just waiting 2 min for the tests to complete. Would you add all info about `obs_vector` etc. to the release notes? And then we make the last `0.6` sub release (it's been more than a year of 0.6 now). 🙂

**Comment by falexwolf** [comment]
Made `v0.6.21`. We can move forward with merging, in my opinion.

**Comment by ivirshup** [comment]
I think it's good to go. Unless anyone else would like to review? @flying-sheep @Koncopd?

**Comment by flying-sheep** [comment]
Things are still incorrectly named “views”.

**Pull request merged**
