### PR TITLE
Add requirements file

### PR DESCRIPTION
**Pull request by ivirshup**
Testing to see if we can restore the `Packages` info for the project by adding the requirements.txt back.

### CODE REVIEW

**Comment by flying-sheep** [comment]
You forgot to add a test that makes sure the requirements aren’t out of sync as we decided

**Comment by ivirshup** [comment]
I want to see if it actually fixes the problem before adding a task to generate it/ make sure it's up to date

**Comment by flying-sheep** [comment]
too bad one has to commit to master for this, but I understand

**Comment by ivirshup** [comment]
Dependencies of our package seem to be back (if a little strange), but dependents are not. I wonder if making a release will trigger that again. It's not obvious to me if Dependabot is even what's being used here. Sadly, got no feedback on the support forum: https://github.community/t/projects-not-listing-dependencies-anymore/168530

**Comment by flying-sheep** [comment]
Yeah, I’m not even sure if GitHub’s aquiring of depandabot means that anything fixed there ends up in GitHub, or if there’s still an independent version …

But I guess that’s what the OSS world gets for deciding for closed source infrastructure …

**Comment by flying-sheep** [comment]
How is it autogenerated? Did you add the test checking if the file is synced?

**Pull request merged**
