### PR TITLE
use obs and var when creating adata from df

### LINKED ISSUE #137: obs is ignored when initializing AnnData with DataFrame
Minimal example:
```python
import anndata
import numpy as np
import pandas as pd

X = pd.DataFrame(np.empty((2,100)))
obs = pd.DataFrame(np.empty((2, 5)))

anndata.AnnData(X=X, obs=obs)
```
Output:
```python
AnnData object with n_obs × n_vars = 2 × 100 
```
Please note, that this `AnnData` has no entries in `obs`, so `obs` was ignored. In contrast, `obs` is set correctly, when I pass an array to X:
```python
anndata.AnnData(X=X.values, obs=obs)
```
Output:
```python
AnnData object with n_obs × n_vars = 2 × 100 
    obs: 0, 1, 2, 3, 4
```

### PR DESCRIPTION
**Pull request by fabianrost84**
fixes #137

### CODE REVIEW

**Comment by flying-sheep** [comment]
Look great! Could you please also test error cases using `with pytest.raises(ValueError, match=r'Index of ...'): ...`

**Comment by fabianrost84** [comment]
Thanks! Sure, I will add the error cases. I was about to ask how do that, because I did not know. So, thanks for letting me know

**Comment by flying-sheep** [comment]
Sure! For the future you should bear in mind that the argument passed to “match” is a regex. But your error messages don’t contain special regex characters so that’s no problem here.

**Comment by fabianrost84** [comment]
great to know, thanks! I just made another correction because the tests failed.

**Comment by flying-sheep** [comment]
Great, thank you very much!

**Pull request merged**
