### PR TITLE
adds support for composing obsm from 1D loom attributes

### PR DESCRIPTION
**Pull request by neuromusic**
implements #131 

tests pass.

I only implemented this for `.obsm` but once I dove in, I realized this same pattern might be relevant for `.varm`?

### CODE REVIEW

**Comment by flying-sheep** [comment]
Thank you, looks great!

> I only implemented this for `.obsm` but once I dove in, I realized this same pattern might be relevant for `.varm`?

Definitely! Please put that one in for symmetry.

**Comment by neuromusic** [comment]
@flying-sheep awesome. I lost bandwidth but will try to implement this for `.varm` soonish

**Comment by neuromusic** [comment]
ok @flying-sheep, this is ready for another review

**Comment by flying-sheep** [comment]
Great, thank you!

**Comment by neuromusic** [comment]
🤸‍♂

**Pull request merged**
