### PR TITLE
to_adata for .raw

### PR DESCRIPTION
**Pull request by falexwolf**
Allows to replace ugly code like
```
adata_new = AnnData(adata.raw.X, var=adata.raw.var, obs=adata.obs, obsm=adata.obsm, uns=adata.uns)
```
with 
```
adata_new = adata.raw.to_adata()
```

### CODE REVIEW

**Comment by falexwolf** [comment]
I don't think there is anything to discuss, here, is there?

**Comment by gokceneraslan** [comment]
Oh I also needed this so much, thanks!

**Comment by fidelram** [comment]
Appreciated. I am doing the ugly way frequently.

**Comment by gokceneraslan** [comment]
Are adata.raw.obsm and adata.obsm pointing to  the same thing? Same goes for uns. If not the same, then the ugly code and the new code are not equivalent.

**Comment by ivirshup** [comment]
`adata.raw.obsm` isn't defined, same for `.raw.uns`, `.raw.obs`, `.raw.obsp`.

**Comment by gokceneraslan** [comment]
ok, that's what I suspect, too. I missed the _adata part in `self._adata.obs.copy `. thanks.

**Comment by gokceneraslan** [comment]
Do we need to add `obsp` to this code, now that neighbors and distances are stored in `obsp`?

**Pull request merged**
