### PR TITLE
Allow pandas >1.1, is_categorical -> is_categorical_dtype

### LINKED ISSUE #419: is_categorical is deprecated in Pandas 1.1, use is_categorical_dtype instead
Apparently is_categorical is deprecated in pandas 1.1, as you probably already know:

https://github.com/pandas-dev/pandas/pull/33385

Here are the instances I can find:

https://github.com/theislab/anndata/blob/master/anndata/_core/anndata.py#L1094

https://github.com/theislab/anndata/blob/master/anndata/_core/anndata.py#L1192

https://github.com/theislab/anndata/blob/master/anndata/tests/test_readwrite.py#L8

Here is how highly_variable_genes look like, a bit annoying:

image

### PR DESCRIPTION
**Pull request by ivirshup**
Fixes #419

### CODE REVIEW

**Comment by flying-sheep** [comment]
whoops, misclicked, sorry.

I wanted to ask if really exactly that version is buggy ad 1.1.1 fixes it?

**Comment by ivirshup** [comment]
I'm very sure – I made the PR to pandas that fixed it!

**Comment by flying-sheep** [comment]
Haha awesome, thank you!

**Comment by diazdc** [comment]
Is this fixed in 0.7.4? I'm still getting the warning. Thanks.

**Comment by ivirshup** [comment]
No, this will be fixed in 0.7.5

**Pull request merged**
