### PR TITLE
update project dependencies: require numpy >= 1.14 and scipy >= 1.0

### PR DESCRIPTION
**Pull request by Hoeze**
See also https://github.com/theislab/anndata/issues/76

### CODE REVIEW

**Comment by Hoeze** [comment]
```python
from anndata import AnnData
E   ImportError: No module named 'anndata'
```
hmm.. Travis configuration problem?

**Comment by flying-sheep** [comment]
can we discuss this in #76 before doing anything?

**Comment by Hoeze** [comment]
Ah sorry I did not see that change ^^

I usually just use '>=' to keep pip from downgrading packages :)

**Comment by flying-sheep** [comment]
yeah, `~=` is pretty unintuitive… it should work like semver’s `^=` but doesn’t.

maybe we should just go explicit and do `numpy>=1.4.0, numpy<2.0.0` and so on…

**Pull request closed without merging**
