### PR TITLE
added layer param to to_df

### PR DESCRIPTION
**Pull request by falexwolf**

### CODE REVIEW

**Comment by ivirshup** [comment]
Looks good! Can it get a test?

**Comment by falexwolf** [comment]
Thanks! Can you merge once this has passed, in case I fell asleep already? 😄

**Comment by falexwolf** [comment]
I hate double quotes so much. 😭

**Comment by falexwolf** [comment]
Can we disable that black makes tests fail because of single quotes? I can't get used to it as I consistently use single-quotes everywhere; this process for every PR is ... so ... annoying.

**Pull request merged**
